// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/79a7fad499369ce70e79e909c0706f391c01336c/react-dnd-html5-backend/react-dnd-html5-backend.d.ts
declare module "react-dnd-html5-backend" {
	import ReactDnd = __ReactDnd;
	
    export enum NativeTypes { FILE, URL, TEXT }
    export function getEmptyImage(): any; // Image
    export default class HTML5Backend implements __ReactDnd.Backend {}
}